# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53d60fbb71daf70ce18cf5d7c73e16c293b81f2ee09990efa691f7b2a132ea28b0338713578a413da1db7ba5d7d992dbe48ad206bfd72d71731b918283c9bf58

test:
  secret_key_base: d7b182dca42b75e3942e02c7ef3d0bb4aacb702f648a33b971baa1682c4f0d7f4e0c5f1ee607bd207e1d82ccb08f45924e619293fb3431b4a297743b3e100240

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
